### ISSUE TITLE
Class Page: Double click on result field leads to double of results

### ISSUE THREAD

**Issue by aykborstelmann** [bjs-org/bjs-web#14]
![image](https://user-images.githubusercontent.com/31162687/76705868-a4fee900-66e3-11ea-9e5f-f09ba82acb5d.png)

If you double click the result button, the results are duplicated.

**Comment by skyliam** [comment]
I dont have this bug.

**Comment by aykborstelmann** [comment]
Well I even have this at the mobil device, please have a look at this. This occurs if you click the result button twice before it even shows up

**Comment by skyliam** [comment]
I found the reason why i dont get this bug, the modal is opening instantly on my pc so i dont even have the chance to double click. I reproduced the bug on my mobile phone.

**Comment by skyliam** [comment]
I think I solved the problem
